version: "4.0"

# ---------------------------
# Example Gitea + Postgres Compose Stack
# This file is a public-safe template with all sensitive details removed.
# Replace values marked with <edit-me> as needed.
# ---------------------------

# Define isolated network for this stack
networks:
  gitea-net:
    external: false

services:
  gitea:
    image: gitea/gitea:1.21.10             # Use official Gitea image (pick latest stable)
    container_name: gitea-svc              # Container name (can be any string)
    hostname: gitea.local                  # Internal container hostname (not public)
    restart: always
    networks:
      - gitea-net
    environment:
      - USER_UID=1000                      # Match UID/GID of host user
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432      # Matches db service name below
      - GITEA__database__NAME=gitea        # Database name
      - GITEA__database__USER=gitea        # Database user
      - GITEA__database__PASSWD=<edit-me>  # Choose strong password
    volumes:
      - ./gitea:/data                      # Persistent app data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # comment ports if fronted by Traefik/NGINX)
     ports:
       - "3000:3000"   # Web UI
       - "222:22"      # SSH access

    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea-db
    hostname: gitea-db
    restart: always
    networks:
      - gitea-net
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=<edit-me>        # Choose strong password
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data  # Persistent database data
